// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: college.proto

package college_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCollegeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Level    int32  `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	Province string `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`
	City     string `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	District string `protobuf:"bytes,7,opt,name=District,proto3" json:"District,omitempty"`
	CreateBy string `protobuf:"bytes,8,opt,name=CreateBy,proto3" json:"CreateBy,omitempty"`
}

func (x *AddCollegeRequest) Reset() {
	*x = AddCollegeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_college_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCollegeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollegeRequest) ProtoMessage() {}

func (x *AddCollegeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_college_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollegeRequest.ProtoReflect.Descriptor instead.
func (*AddCollegeRequest) Descriptor() ([]byte, []int) {
	return file_college_proto_rawDescGZIP(), []int{0}
}

func (x *AddCollegeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddCollegeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCollegeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AddCollegeRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AddCollegeRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddCollegeRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddCollegeRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddCollegeRequest) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

type AddCollegeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddCollegeResponse) Reset() {
	*x = AddCollegeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_college_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCollegeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollegeResponse) ProtoMessage() {}

func (x *AddCollegeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_college_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollegeResponse.ProtoReflect.Descriptor instead.
func (*AddCollegeResponse) Descriptor() ([]byte, []int) {
	return file_college_proto_rawDescGZIP(), []int{1}
}

type UpdateCollegeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Code         string `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Level        int32  `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	Province     string `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`
	City         string `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	District     string `protobuf:"bytes,7,opt,name=District,proto3" json:"District,omitempty"`
	LastModifyBy string `protobuf:"bytes,8,opt,name=LastModifyBy,proto3" json:"LastModifyBy,omitempty"`
}

func (x *UpdateCollegeRequest) Reset() {
	*x = UpdateCollegeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_college_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCollegeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollegeRequest) ProtoMessage() {}

func (x *UpdateCollegeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_college_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollegeRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollegeRequest) Descriptor() ([]byte, []int) {
	return file_college_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCollegeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCollegeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCollegeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateCollegeRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdateCollegeRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UpdateCollegeRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateCollegeRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateCollegeRequest) GetLastModifyBy() string {
	if x != nil {
		return x.LastModifyBy
	}
	return ""
}

type UpdateCollegeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCollegeResponse) Reset() {
	*x = UpdateCollegeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_college_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCollegeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollegeResponse) ProtoMessage() {}

func (x *UpdateCollegeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_college_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollegeResponse.ProtoReflect.Descriptor instead.
func (*UpdateCollegeResponse) Descriptor() ([]byte, []int) {
	return file_college_proto_rawDescGZIP(), []int{3}
}

var File_college_proto protoreflect.FileDescriptor

var file_college_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x64, 0x64, 0x22, 0xc9, 0x01, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x22, 0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd4, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4c, 0x61, 0x73,
	0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x42, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x42, 0x79, 0x22, 0x17, 0x0a,
	0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x90, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65,
	0x12, 0x16, 0x2e, 0x61, 0x64, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x64, 0x64, 0x2e, 0x41,
	0x64, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x46, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x67, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x64, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x61, 0x64, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x67, 0x65, 0x2d, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_college_proto_rawDescOnce sync.Once
	file_college_proto_rawDescData = file_college_proto_rawDesc
)

func file_college_proto_rawDescGZIP() []byte {
	file_college_proto_rawDescOnce.Do(func() {
		file_college_proto_rawDescData = protoimpl.X.CompressGZIP(file_college_proto_rawDescData)
	})
	return file_college_proto_rawDescData
}

var file_college_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_college_proto_goTypes = []interface{}{
	(*AddCollegeRequest)(nil),     // 0: add.AddCollegeRequest
	(*AddCollegeResponse)(nil),    // 1: add.AddCollegeResponse
	(*UpdateCollegeRequest)(nil),  // 2: add.UpdateCollegeRequest
	(*UpdateCollegeResponse)(nil), // 3: add.UpdateCollegeResponse
}
var file_college_proto_depIdxs = []int32{
	0, // 0: add.College.AddCollege:input_type -> add.AddCollegeRequest
	2, // 1: add.College.UpdateCollege:input_type -> add.UpdateCollegeRequest
	1, // 2: add.College.AddCollege:output_type -> add.AddCollegeResponse
	3, // 3: add.College.UpdateCollege:output_type -> add.UpdateCollegeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_college_proto_init() }
func file_college_proto_init() {
	if File_college_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_college_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCollegeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_college_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCollegeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_college_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCollegeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_college_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCollegeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_college_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_college_proto_goTypes,
		DependencyIndexes: file_college_proto_depIdxs,
		MessageInfos:      file_college_proto_msgTypes,
	}.Build()
	File_college_proto = out.File
	file_college_proto_rawDesc = nil
	file_college_proto_goTypes = nil
	file_college_proto_depIdxs = nil
}
