// Code generated by goctl. DO NOT EDIT!
// Source: college.proto

package college

import (
	"context"

	"github.com/proeditor/mengnan/college/rpc/college-rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCollegeRequest     = college_rpc.AddCollegeRequest
	AddCollegeResponse    = college_rpc.AddCollegeResponse
	UpdateCollegeRequest  = college_rpc.UpdateCollegeRequest
	UpdateCollegeResponse = college_rpc.UpdateCollegeResponse

	College interface {
		AddCollege(ctx context.Context, in *AddCollegeRequest, opts ...grpc.CallOption) (*AddCollegeResponse, error)
		UpdateCollege(ctx context.Context, in *UpdateCollegeRequest, opts ...grpc.CallOption) (*UpdateCollegeResponse, error)
	}

	defaultCollege struct {
		cli zrpc.Client
	}
)

func NewCollege(cli zrpc.Client) College {
	return &defaultCollege{
		cli: cli,
	}
}

func (m *defaultCollege) AddCollege(ctx context.Context, in *AddCollegeRequest, opts ...grpc.CallOption) (*AddCollegeResponse, error) {
	client := college_rpc.NewCollegeClient(m.cli.Conn())
	return client.AddCollege(ctx, in, opts...)
}

func (m *defaultCollege) UpdateCollege(ctx context.Context, in *UpdateCollegeRequest, opts ...grpc.CallOption) (*UpdateCollegeResponse, error) {
	client := college_rpc.NewCollegeClient(m.cli.Conn())
	return client.UpdateCollege(ctx, in, opts...)
}
