// Code generated by goctl. DO NOT EDIT!
// Source: college.proto

package server

import (
	"context"

	"rpc/college/rpc"
	"rpc/internal/logic"
	"rpc/internal/svc"
)

type CollegeServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedCollegeServer
}

func NewCollegeServer(svcCtx *svc.ServiceContext) *CollegeServer {
	return &CollegeServer{
		svcCtx: svcCtx,
	}
}

func (s *CollegeServer) AddCollege(ctx context.Context, in *rpc.CollegeAddRequest) (*rpc.CollegeAddResponse, error) {
	l := logic.NewAddCollegeLogic(ctx, s.svcCtx)
	return l.AddCollege(in)
}

func (s *CollegeServer) UpdateCollege(ctx context.Context, in *rpc.CollegeUpdateRequest) (*rpc.CollegeUpdateResponse, error) {
	l := logic.NewUpdateCollegeLogic(ctx, s.svcCtx)
	return l.UpdateCollege(in)
}
