// Code generated by goctl. DO NOT EDIT!
// Source: college.proto

package server

import (
	"context"

	"collegerpc/collegerpc"
	"collegerpc/internal/logic"
	"collegerpc/internal/svc"
)

type CollegeServer struct {
	svcCtx *svc.ServiceContext
	collegerpc.UnimplementedCollegeServer
}

func NewCollegeServer(svcCtx *svc.ServiceContext) *CollegeServer {
	return &CollegeServer{
		svcCtx: svcCtx,
	}
}

func (s *CollegeServer) AddCollege(ctx context.Context, in *collegerpc.CollegeAddRequest) (*collegerpc.CollegeAddResponse, error) {
	l := logic.NewAddCollegeLogic(ctx, s.svcCtx)
	return l.AddCollege(in)
}

func (s *CollegeServer) UpdateCollege(ctx context.Context, in *collegerpc.CollegeUpdateRequest) (*collegerpc.CollegeUpdateResponse, error) {
	l := logic.NewUpdateCollegeLogic(ctx, s.svcCtx)
	return l.UpdateCollege(in)
}
